# Generated by Django 5.2 on 2026-01-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['codigo'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='academico.periodoacademico'),
        ),
    ]
