# Generated by Django 5.2 on 2026-01-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_periodoacademico_alter_asignatura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='periodo_academico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='academico.periodoacademico'),
        ),
    ]
