# Generated by Django 5.2.9 on 2026-01-01 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_asignatura_periodo_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='facultad',
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'ordering': ['nombre'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AddField(
            model_name='facultad',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('pregrado', 'Pregrado'), ('posgrado', 'Posgrado')], max_length=15)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=15)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academico.facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanCarreraAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('creditos_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_carrera', to='academico.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_asignaturas', to='academico.carrera')),
            ],
            options={
                'verbose_name': 'Plan Carrera Asignatura',
                'verbose_name_plural': 'Planes Carrera Asignaturas',
                'ordering': ['carrera', 'semestre'],
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='asignaturas', through='academico.PlanCarreraAsignatura', to='academico.carrera'),
        ),
    ]
