# Generated by Django 5.2.9 on 2026-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_facultad_carrera_plan'),
        ('usuarios', '0003_facultad_carrera_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.AddConstraint(
            model_name='carrera',
            constraint=models.UniqueConstraint(fields=('facultad', 'codigo'), name='uniq_carrera_codigo_por_facultad'),
        ),
        migrations.AddConstraint(
            model_name='plancarreraasignatura',
            constraint=models.UniqueConstraint(fields=('carrera', 'asignatura'), name='uniq_carrera_asignatura'),
        ),
    ]
