# Generated by Django 5.2 on 2026-01-02 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_facultad_carrera_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='coordinador',
            field=models.OneToOneField(blank=True, help_text='Coordinador designado para esta facultad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facultad_coordinador', to=settings.AUTH_USER_MODEL),
        ),
    ]
