# Generated by Django 5.2 on 2026-01-02 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_facultad_coordinador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='profesores_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Profesores adicionales que enseñan esta asignatura', related_name='asignaturas_adicionales', to=settings.AUTH_USER_MODEL),
        ),
    ]
