# Generated by Django 5.2.9 on 2026-01-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_asignatura_profesores_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancarreraasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_carrera', to='academico.asignatura'),
        ),
    ]
