# Generated by Django 5.2.9 on 2026-01-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alter_plancarreraasignatura_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='prerrequisitos',
            field=models.ManyToManyField(blank=True, help_text='Asignaturas que son requisito para esta', related_name='asignaturas_dependientes', to='academico.asignatura'),
        ),
    ]
