# Generated by Django 5.2 on 2026-01-08 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula-Asignatura', 'verbose_name_plural': 'Matrículas-Asignaturas'},
        ),
        migrations.AddField(
            model_name='matricula',
            name='horario',
            field=models.CharField(blank=True, help_text='Horario de estudio: Ejemplo Lunes 8-10am o formato JSON', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to=models.Q(('rol', 'estudiante'), ('roles__tipo', 'estudiante'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
    ]
