# Generated by Django 5.2 on 2025-12-29 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.ForeignKey(blank=True, help_text='Facultad asignada (solo para admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='academico.facultad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de identificación del usuario', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='programa',
            field=models.ForeignKey(blank=True, help_text='Programa académico (solo para estudiantes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.programa'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
