# Generated by Django 5.2.9 on 2026-01-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_facultad_carrera_plan'),
        ('usuarios', '0002_usuario_estado_usuario_facultad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='programa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera académica (solo para estudiantes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.carrera'),
        ),
    ]
