# Generated by Django 5.2.9 on 2025-12-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_asignatura_facultad_usuario_facultad_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de identificación del usuario', max_length=30, null=True, unique=True),
        ),
    ]
