# Generated by Django 5.2 on 2026-01-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_facultad_carrera_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Un usuario puede tener múltiples roles', related_name='usuarios', to='usuarios.rol'),
        ),
    ]
