# Generated by Django 5.2 on 2026-01-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rol_alter_usuario_rol_usuario_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=20, null=True),
        ),
    ]
