# Generated by Django 5.2 on 2026-01-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del permiso (ej: crear_asignatura, calificar_tarea)', max_length=100, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del permiso')),
                ('modulo', models.CharField(choices=[('academico', 'Académico'), ('usuarios', 'Usuarios'), ('reportes', 'Reportes'), ('notificaciones', 'Notificaciones')], help_text='Módulo al que pertenece el permiso', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el permiso está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos_asignados',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos asignados a este rol', related_name='roles', to='usuarios.permiso'),
        ),
    ]
