# Generated by Django 5.2.9 on 2026-01-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluaciones', '0002_entregatarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recordatorio', models.CharField(choices=[('D3_ESTUDIANTE', '3 días antes (estudiante)'), ('D1_ESTUDIANTE', '1 día antes (estudiante)'), ('D1_DOCENTE', '1 día antes (docente)')], max_length=20)),
                ('scheduled_for', models.DateTimeField(help_text='Fecha/hora programada para enviar el recordatorio')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha/hora real de envío', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_vencimiento', to='evaluaciones.tarea')),
            ],
            options={
                'indexes': [models.Index(fields=['sent_at', 'scheduled_for'], name='notificacio_sent_at_705344_idx')],
                'constraints': [models.UniqueConstraint(fields=('tarea', 'tipo_recordatorio'), name='uniq_recordatorio_por_tarea_y_tipo')],
            },
        ),
    ]
