# Generated by Django 5.2.9 on 2026-01-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0009_asignatura_prerrequisitos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la tarea o examen', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la tarea', null=True)),
                ('tipo_tarea', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('quiz', 'Quiz'), ('proyecto', 'Proyecto'), ('participacion', 'Participación')], default='tarea', help_text='Tipo de evaluación', max_length=20)),
                ('peso_porcentual', models.DecimalField(decimal_places=2, help_text='Peso en porcentaje (0-100). Ej: 15.50 para 15.5%', max_digits=5)),
                ('fecha_publicacion', models.DateTimeField(help_text='Fecha y hora en que la tarea será visible para estudiantes')),
                ('fecha_vencimiento', models.DateTimeField(help_text='Fecha y hora límite para entregar la tarea')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', help_text='Estado actual de la tarea', max_length=20)),
                ('permite_entrega_tardia', models.BooleanField(default=False, help_text='Permite que estudiantes entreguen después del vencimiento')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto con instrucciones (PDF, DOCX, etc.)', null=True, upload_to='tareas/adjuntos/%Y/%m/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(help_text='Asignatura a la que pertenece esta tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academico.asignatura')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha_publicacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('peso_porcentual__gte', 0), ('peso_porcentual__lte', 100)), name='peso_valido')],
            },
        ),
    ]
