# Generated by Django 5.2 on 2026-01-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_entrega', models.FileField(help_text='Archivo entregado por el estudiante', upload_to='tareas/entregas/%Y/%m/')),
                ('comentarios_estudiante', models.TextField(blank=True, help_text='Comentarios adicionales del estudiante', null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la entrega')),
                ('estado_entrega', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('revisada', 'Revisada'), ('calificada', 'Calificada'), ('tardia', 'Entrega tardía')], default='pendiente', help_text='Estado de la entrega', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación obtenida (0-100)', max_digits=5, null=True)),
                ('comentarios_docente', models.TextField(blank=True, help_text='Retroalimentación del docente', null=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, help_text='Fecha en que el docente calificó', null=True)),
                ('estudiante', models.ForeignKey(help_text='Estudiante que realiza la entrega', on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea a la que corresponde esta entrega', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='evaluaciones.tarea')),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
                'ordering': ['-fecha_entrega'],
                'constraints': [models.CheckConstraint(condition=models.Q(('calificacion__isnull', True), models.Q(('calificacion__gte', 0), ('calificacion__lte', 100)), _connector='OR'), name='calificacion_valida')],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
